{{- if lookup "v1" "Namespace" "" "argo" }}
apiVersion: v1
kind: Secret
metadata:
  name: ml-system-secrets
  namespace: argo
type: Opaque
stringData:
  lakefs-access-key-id: {{ .Values.secrets.lakefs.accessKeyId | quote }}
  lakefs-secret-access-key: {{ .Values.secrets.lakefs.secretAccessKey | quote }}
{{- end }}
