apiVersion: v1
kind: Secret
metadata:
  name: ml-system-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  minio-access-key: {{ .Values.secrets.minioAccessKey | quote }}
  minio-secret-key: {{ .Values.secrets.minioSecretKey | quote }}
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  lakefs-access-key-id: {{ .Values.secrets.lakefs.accessKeyId | quote }}
  lakefs-secret-access-key: {{ .Values.secrets.lakefs.secretAccessKey | quote }}
  lakefs-encrypt-secret-key: {{ .Values.secrets.lakefs.encryptSecretKey | quote }}
